### ISSUE TITLE
[Amadeus] Migrate Weeb

### ISSUE THREAD

**Issue by Czechbol** [pumpkin-py/pumpkin-fun#2]
We need to migrate the Weeb cog from Amadeus to Fun (as Weeb submodule). 

See the cog [here](https://github.com/Czechbol/Amadeus/blob/master/cogs/weeb.py).

The cog doesn't use a database and is using the Nhentai API so this will be fairly a easy port.

Please rewrite using the `aiohttp` library instead of `requests`. Do not use the legendary `hentai` library as it uses `requests` which would slow the bot down.

Feel free to rewrite any part of the cog to make it better/more readable

**Comment by Oswinska** [comment]
I'll give this a shot.

**Comment by Czechbol** [comment]
Resolved in #14
