### ISSUE TITLE
Random: Update the 'pick' command

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin-fun#9]
Instead of simply taking a list of arguments
```py
async def pick(self, ctx, *args):
```
update the code so that the first two arguments are required. This will force the users to add at least two arguments to be picked from. It should still be possible to submit an unlimited number of arguments.

**Comment by SebGoliot** [comment]
Hi, I can work on this, is there anything I need to know beforehand ?

**Comment by sinus-x** [comment]
@SebGoliot Hi. Do you have any experience with Discord and discord.py? We require the contributors to test the command before opening a PR with their change.

If you didn'ŧ do any Discord bot development before, but you'd like to try it, you can go look at [our documentation](https://pumpkinpy.readthedocs.io/en/latest/installation/03-development.html). If you are looking for easy Hacktoberfest issues that require little-to-no setup, I'm afraid it would be easier for you to offer your contributon to some other project.

**Comment by SebGoliot** [comment]
Yes I have some experience with discord.py, so it won't be a problem.

**Comment by sinus-x** [comment]
Okay then. Everything important should be in the issue description. Just make sure the arguments have some meaninful names, otherwise it's up to you.

**Comment by sinus-x** [comment]
@SebGoliot Hi, are you planning on working on this issue this weekend, or have you lost interest over it? We want to give the opportunity to work on those easy issues to as many Hacktoberfest contributors as possible, and you're blocking this one.

**Comment by sinus-x** [comment]
@SebGoliot Oh, sorry. I assumed the issue got auto-closed, but this is not the case. We usually write
```
Resolves #11
```
into the commit description, which GitHub picks up and closes the issue when the PR gets merged.
